const RUNES = [
  {g:"ᚠ",name:"Fehu",sub:"Cattle · Wealth · sound of F",
   verse:["Wealth is a comfort to all,","yet each must share it well,","for it stirs strife among kin,","and the wolf is raised in the woods."],
   meaning:"Fehu is movable wealth. Cattle in the old world, money and resources in ours. It is abundance that flows rather than sits, and the poem names its double edge: what you gather can feed you or set your kin against one another. The rune asks not whether you have, but whether it moves. Held too tightly, wealth breeds the wolf. Kept in flow, given and circulated, it nourishes. Today, look at what you're holding and ask what it's doing — standing still, or feeding something.",source:"Norwegian Rune Poem, st. 1; Old English Rune Poem, st. 1"},

  {g:"ᚢ",name:"Uruz",sub:"Aurochs · Primal Strength · sound of U",
   verse:["Slag comes from poor iron;","the reindeer runs hard","over the frozen snow."],
   meaning:"Uruz is the wild ox, the untamed vital force that runs before it's broken. The poem sets slag against the running reindeer: raw material that failed the forge, and raw power that endures the hard ground. This is strength before it's shaped, health and drive in their rough form. Uruz doesn't ask you to be refined today. It asks you to be strong, to move over hard ground under your own power, to trust the vitality that was in you before anyone tried to smooth it down. The unbroken thing has its own wisdom.",source:"Norwegian Rune Poem, st. 2; Old English Rune Poem, st. 2"},

  {g:"ᚦ",name:"Thurisaz",sub:"Thurs · the Giant · sound of Th",
   verse:["The thurs brings torment;","few are made glad","by hardship."],
   meaning:"Thurs is the giant, the thorn, the force that breaks resistance. It is the most dangerous rune to hold lightly, and the poem doesn't soften it. Thurisaz is raw reactive power, the striking force, the thorn that defends and the thorn that wounds. It cuts both ways and it doesn't care which. Today it asks for care in how you meet resistance. There is a force available to you that breaks through obstacles, but it breaks other things too. Use it deliberately, or not at all. The thorn defends the blackthorn — and draws blood from the hand that grips it wrong.",source:"Norwegian Rune Poem, st. 3; Old Icelandic Rune Poem, st. 3"},

  {g:"ᚨ",name:"Ansuz",sub:"the God · Breath · sound of A",
   verse:["The god is the way of most journeys,","the mouth of speech,","the breath that carries the word."],
   meaning:"Ansuz is Odin's rune: breath, speech, the sacred word that shapes what it names. It is the power of communication and the force behind inspiration, the message that arrives from beyond the ordinary mind. Where Fehu asks about wealth and Uruz about strength, Ansuz asks about voice. What are you saying, and what is being said to you? Today, pay attention to words — the ones you speak, the ones you withhold, and the ones that seem to arrive unbidden. The breath carries the word, and the word carries power. Choose it well.",source:"Norwegian Rune Poem, st. 4; Old English Rune Poem, st. 4"},

  {g:"ᚱ",name:"Raidho",sub:"the Ride · Journey · sound of R",
   verse:["Riding is worst for horses;","Reginn forged","the finest sword."],
   meaning:"Raidho is the ride, the journey, right motion and rhythm. The poem holds two truths: the road is hard on the one who travels it, and great things are forged along the way. This is movement with purpose, the difference between wandering and traveling. Raidho governs the path taken deliberately, the wheel that turns in its proper time. Today it asks whether your motion has direction. Not speed, direction. The horse tires on the long road, but the journey shapes the traveler, and the right road is worth the wear it costs you.",source:"Norwegian Rune Poem, st. 5; Old English Rune Poem, st. 5"},

  {g:"ᚲ",name:"Kenaz",sub:"the Torch · Fire of Craft · sound of K",
   verse:["The torch is known by its flame;","it reveals what the dark had hidden,","and warms the hand that keeps it."],
   meaning:"Kenaz is the controlled fire — the torch, the forge-flame, the light of craft and revelation. Unlike wildfire, this is fire held and directed, the heat that shapes iron and the light that shows the hidden thing. It is knowledge won through making, skill earned at the anvil. Today Kenaz asks what you're forging and what you're willing to see. The torch reveals, and not everything it shows is comfortable. But the same flame that exposes also warms, and the same heat that burns also shapes. Tend your fire. It is how the raw becomes the made.",source:"Norwegian Rune Poem, st. 6; Old English Rune Poem, st. 6"},

  {g:"ᚷ",name:"Gebo",sub:"the Gift · Exchange · sound of G",
   verse:["A gift calls for a gift;","the bond is made","in the giving and the taking."],
   meaning:"Gebo is the gift, and the sacred law of exchange that runs beneath all relationship. A gift given creates a bond; a gift received carries an obligation. This is not transaction but reciprocity, the web of giving that ties people, and people to the gods. Gebo has no reversed form — a gift is a gift from either side. Today it asks about your exchanges. What have you been given, and what have you offered? Balance matters here. To take without giving starves the bond; to give without receiving exhausts it. The thread holds when it runs both ways.",source:"Old English Rune Poem, st. 7"},

  {g:"ᚹ",name:"Wunjo",sub:"Joy · Harmony · sound of W",
   verse:["Joy comes to the one","who knows few troubles,","and holds pain and sorrow at bay."],
   meaning:"Wunjo is joy — not the giddy kind, but the deep contentment of things in their right place. It is harmony, belonging, the gladness of kin gathered and work well done. The poem is honest that this joy comes to those free of grief, which makes it something to protect rather than assume. Wunjo closes the first aett, the reward at the end of the row's early labors. Today it asks where your genuine gladness lives, and whether you're tending it. Joy is not the absence of hardship. It's what you build in the clearings between.",source:"Old English Rune Poem, st. 8"},

  {g:"ᚺ",name:"Hagalaz",sub:"Hail · Disruption · sound of H",
   verse:["Hail is the coldest of grains;","it falls hard from the sky,","then melts to water and feeds the ground."],
   meaning:"Hagalaz is hail: the sudden destructive force that arrives from above and cannot be argued with. It is the storm that flattens the crop, the crisis that breaks the plan. But the poem holds the turn — hail is frozen water, and when it melts it feeds the very ground it battered. This is disruption that transforms, the necessary destruction that clears the way. Today Hagalaz asks how you meet what you can't control. The hail will fall. You don't choose that. But frozen sky becomes spring water, and what breaks you open can also become what feeds what comes next.",source:"Norwegian Rune Poem, st. 7; Old English Rune Poem, st. 9"},

  {g:"ᚾ",name:"Naudhiz",sub:"Need · Necessity · sound of N",
   verse:["Need makes a hard master;","yet the naked are warmed by the fire","that necessity kindles."],
   meaning:"Naudhiz is need — constraint, hardship, the friction of necessity. It is the fetter that binds and the fire kindled by rubbing wood in the cold. The poem names both: need is a hard master, and need is what teaches the freezing to make fire. This is the rune of lack that forces resourcefulness, the pressure that reveals what you're capable of. Today Naudhiz asks what your constraints are teaching you. Nobody chooses need. But the need-fire is real — the strength that only appears when there's no other way, the warmth kindled precisely because you had to.",source:"Norwegian Rune Poem, st. 8; Old English Rune Poem, st. 10"},

  {g:"ᛁ",name:"Isa",sub:"Ice · Stillness · sound of I",
   verse:["Ice we call the broad bridge;","the blind must be led across it,","for it hides the deep water below."],
   meaning:"Isa is ice: stillness, stasis, the great pause. It is the frozen river that becomes a bridge, beautiful and treacherous, hiding moving water beneath its stillness. This is the place of silence where the sacred is found, and also the trap of things frozen too long. Isa asks for patience and for caution both. Today, something may need to stop moving so you can see it clearly. But watch the ice — what looks solid may be thin, and what looks like rest may be avoidance. Stillness is a source and a hazard. Know which one you're standing on.",source:"Norwegian Rune Poem, st. 9; Old English Rune Poem, st. 11"},

  {g:"ᛃ",name:"Jera",sub:"Harvest · the Year · sound of J/Y",
   verse:["Harvest is the joy of all,","when the good year comes","and the earth gives up her gift."],
   meaning:"Jera is the harvest, the turning year, the reward that comes only in its proper season. It is the cycle completed — seed to growth to gathering — and the patience that cycle demands. Nothing about Jera is sudden; it is the rune of right timing, of effort that pays off when the time is ripe and not before. Today Jera asks what you've planted and whether you're letting it ripen. The harvest can't be rushed, and the good year comes to those who did the early work and then waited. What you tend now, you gather later. Both parts are the work.",source:"Norwegian Rune Poem, st. 10; Old English Rune Poem, st. 12"},

  {g:"ᛇ",name:"Eihwaz",sub:"Yew · the World-Tree · sound of Ei",
   verse:["The yew stands green through winter;","its roots run deep,","its fire burns slow and long."],
   meaning:"Eihwaz is the yew — the evergreen that endures winter, the wood of the bow, the axis that connects the worlds. It is death and endurance held together: the yew is poisonous and eternal, standing green when all else is bare. This is the rune of deep connection between realms, the spine of the World-Tree, the truth that runs through the core. Today Eihwaz asks what endures in you when everything else falls away. The yew doesn't drop its needles. Deep roots, slow fire, the green that outlasts the cold. Find the thing in you that winter can't touch, and stand on it.",source:"Old English Rune Poem, st. 13"},

  {g:"ᛈ",name:"Perthro",sub:"the Lot-Cup · Fate · sound of P",
   verse:["The lot-cup is play and laughter","among the bold,","where fate is cast and read."],
   meaning:"Perthro is the dice-cup, the vessel of chance and fate, the mystery of what is hidden and what is drawn. It is the rune of wyrd itself — the woven layers of what was, what is, and what becomes — and of divination, the reading of patterns not yet visible. Perthro governs the unknown and the unfolding. Today it asks how you hold uncertainty. The lot is cast in play among the bold, not in dread. What comes is partly chance and partly the pattern you've already woven. You can't see the whole board. You can choose how you meet what's dealt.",source:"Old English Rune Poem, st. 14"},

  {g:"ᛉ",name:"Algiz",sub:"Elk · Protection · sound of Z",
   verse:["The elk-sedge grows in the marsh;","it wounds the hand","that grasps it wrongly."],
   meaning:"Algiz is the ward — the elk, the raised hand, the sedge-grass that cuts the careless grip. It is protection, the shield-rune, the connection between the human and the divine that guards the one who reaches upward. This is defense that is also reaching, the boundary that is also a bridge to higher things. Today Algiz asks what you're protecting and how you're standing. The sedge defends itself by its own nature — not by attacking, but by being what it is. Raise your guard, root your ground, reach toward what's higher than you. Protection is a posture, not a wall.",source:"Old English Rune Poem, st. 15"},

  {g:"ᛊ",name:"Sowilo",sub:"the Sun · Victory · sound of S",
   verse:["The sun is the light of the land;","I bow before the holy power","that never fails to return."],
   meaning:"Sowilo is the sun — the wheel of light, the force that guides and does not fail. It is victory, wholeness, the solar power that burns through fog and shows the way. Where Isa freezes and Hagalaz destroys, Sowilo warms and reveals. It is the rune of the goal reached and the light that never truly dies, only sets to rise again. Today Sowilo asks what you're steering toward. The sun keeps its course without hurry and without doubt, and it returns every time. Find your own true north and hold it. The light comes back. It always comes back.",source:"Norwegian Rune Poem, st. 11; Old English Rune Poem, st. 16"},

  {g:"ᛏ",name:"Tiwaz",sub:"Tyr · Justice · sound of T",
   verse:["Tyr is the one-handed god;","he keeps his oath","though it cost him his hand."],
   meaning:"Tiwaz is Tyr, the sky-god of justice and sacrifice — the one who placed his hand in the wolf's mouth so the binding would hold, and lost it keeping his word. It is the rune of law, honor, the price of doing what's right. Tiwaz points upward like a spear: direct, disciplined, willing to pay. Today it asks what you stand for and what you'd sacrifice to keep faith with it. Tyr knew the cost and paid it anyway. That's the rune — not comfort, but integrity. The oath kept though it costs you. The right thing done though it takes something from you.",source:"Norwegian Rune Poem, st. 12; Old English Rune Poem, st. 17"},

  {g:"ᛒ",name:"Berkano",sub:"Birch · Growth · sound of B",
   verse:["The birch is greenest of leaves;","it grows without seed","and quietly renews the world."],
   meaning:"Berkano is the birch — the mother-tree, the rune of growth, birth, and quiet renewal. The birch is the first tree to return to cleared ground, greening without apparent seed, healing the land by simply growing. This is gentle generative power, the nurturing force that tends what is coming into being. Today Berkano asks what you're bringing to life, and whether you're giving it room to grow. Not all growth is loud. The birch doesn't force — it renews, softly and steadily, and the forest follows. Tend the new thing. Protect what's just beginning. Growth is its own kind of strength.",source:"Norwegian Rune Poem, st. 13; Old English Rune Poem, st. 18"},

  {g:"ᛖ",name:"Ehwaz",sub:"the Horse · Partnership · sound of E",
   verse:["The horse is the joy of nobles,","proud on its hooves,","trusted where warriors meet."],
   meaning:"Ehwaz is the horse — but more than the animal, it is the bond between horse and rider, the trust that lets two move as one. It is partnership, loyalty, the harmony of a team that carries each other. Where Raidho is the journey, Ehwaz is the one you journey with. Today it asks about your partnerships — the people and forces you move alongside, and whether the trust between you runs true. The horse and rider are only powerful together. Neither alone crosses the hard country. Find your true companions, and be one. What carries you deserves your faith.",source:"Old English Rune Poem, st. 19"},

  {g:"ᛗ",name:"Mannaz",sub:"the Human · Self · sound of M",
   verse:["Man is the joy of man,","and the increase of the earth;","yet each must fail the other in the end."],
   meaning:"Mannaz is the human — humanity, the self, the mind that knows itself and the community that shapes it. The poem holds a hard truth: people are the delight of people, and people fail one another, both true at once. This is the rune of what it means to be a person among persons, mortal and reflective and bound to others. Today Mannaz asks you to see yourself clearly, neither inflated nor diminished. You are one of many, made by your kin and destined to part from them. Know your own measure. The examined self is the beginning of every real work.",source:"Norwegian Rune Poem, st. 14; Old English Rune Poem, st. 20"},

  {g:"ᛚ",name:"Laguz",sub:"Water · the Deep · sound of L",
   verse:["Water is the sea the ship crosses,","wide and unknowable,","carrying life in its dark."],
   meaning:"Laguz is water — the sea, the deep, the flow of the unconscious and the intuitive. It is life-giving and unknowable, the element that carries and the element that drowns. This is the rune of instinct, dreams, the currents beneath the surface mind. It rewards those who trust the flow and warns those who fight it. Today Laguz asks what your intuition is telling you beneath the noise of thought. The deep water holds things the daylight mind can't reach. Don't force the current. Feel where it's already moving, and let it carry you toward what you couldn't have reasoned your way to.",source:"Norwegian Rune Poem, st. 15; Old English Rune Poem, st. 21"},

  {g:"ᛜ",name:"Ingwaz",sub:"Ing · the Seed · sound of Ng",
   verse:["Ing was first seen among men,","then departed over the waves;","the seed waits in the dark for its season."],
   meaning:"Ingwaz is Ing, the earth-god, the seed held in the dark until its time. It is potential gathered and stored, energy sealed away to be released when the season turns. Unlike Jera's completed cycle, Ingwaz is the pregnant pause before — the gestation, the held breath, the work done quietly underground. Today Ingwaz asks what you're incubating. Not everything should be visible yet. Some things need the dark to gather force, the sealed season before the sprouting. Trust what's growing where it can't be seen. The seed doesn't rush. It waits, whole and ready, for the ground to be right.",source:"Old English Rune Poem, st. 22"},

  {g:"ᛞ",name:"Dagaz",sub:"Day · Breakthrough · sound of D",
   verse:["Day is the lord's sending,","the light beloved of all,","hope and comfort to rich and poor alike."],
   meaning:"Dagaz is day — the dawn, the breakthrough, the moment darkness turns to light. It is awakening, the sudden clarity that changes everything, the threshold between one state and the next. Dagaz sits at the edge where opposites meet: the balance-point of dawn and dusk, the transformation that can't be undone once it's happened. Today Dagaz asks what's ready to break through. Some changes come gradually, and some arrive all at once, like daybreak — sudden, total, and beloved. If something in you is turning toward the light, let it. The day comes for everyone. Yours may be arriving now.",source:"Old English Rune Poem, st. 23"},

  {g:"ᛟ",name:"Othala",sub:"Ancestral Land · Legacy · sound of O",
   verse:["The homeland is dear to every man;","there he holds his own,","and stands on the ground of his kin."],
   meaning:"Othala is the ancestral land — inheritance, home, the ground your kin held before you and the legacy you keep. It is the rune of belonging, of what is truly yours by blood and by bond, and of the responsibility that comes with holding it. Othala closes the row: the journey returns to the hearth. Today it asks what you've inherited and what you'll pass on. Not just land, but values, craft, the tended ground of who you are. You stand on what came before you. Hold it well, add to it, and leave it stronger than you found it. That is the whole work, in the end.",source:"Old English Rune Poem, st. 24"}
];
const DEITIES = [
  {name:"Odin",epithet:"the Allfather, the Wanderer",domain:"Wisdom · War · the Runes · Poetry",
   blurb:"Chief of the Æsir and the restless seeker of knowledge. Odin hung nine nights on the World-Tree, pierced by his own spear, to win the runes from the deep. He trades an eye for wisdom, wanders the worlds in a grey cloak, and gathers the slain to Valhalla. He is the god who pays for what he learns, and always pays willingly.",
   brings:"insight won through sacrifice, the courage to seek what's hidden, mastery of word and rune",
   source:"Hávamál 138-145, Poetic Edda"},

  {name:"Frigg",epithet:"Queen of Asgard",domain:"Foresight · Marriage · the Hearth · Fate",
   blurb:"Wife of Odin and foremost of the goddesses. Frigg knows the fate of all things but speaks it to none, holding her knowing in silence. She is the weaver at the loom of the household and the protector of what is built and kept. Her grief for Baldr is the grief of a mother who saw what was coming and could not turn it.",
   brings:"quiet foresight, the strength of the keeper, protection of home and bond",
   source:"Gylfaginning, ch. 35 & 49, Snorri's Edda"},

  {name:"Freya",epithet:"Lady of the Vanir",domain:"Love · Seidr · War · the Slain",
   blurb:"Goddess of love and magic, and no soft figure. Freya rides a chariot drawn by cats, wears the necklace Brísingamen, and takes half the battle-slain to her hall Fólkvangr, Odin taking the rest. She is the mistress of Seidr, the fate-shaping magic, and taught it even to the gods. Desire and death, magic and war, all held in one hand.",
   brings:"the power of Seidr, the fierceness beneath beauty, sovereignty over your own desire",
   source:"Grímnismál 14; Gylfaginning, ch. 24"},

  {name:"Thor",epithet:"the Thunderer",domain:"Storm · Protection · Strength · the Common Folk",
   blurb:"Defender of gods and humankind, wielder of the hammer Mjölnir. Thor rides the storm in a goat-drawn chariot and stands between the ordered world and the giants who would unmake it. He is the least subtle and the most beloved of the gods, the one the working people called on. Where Odin schemes, Thor simply stands his ground and swings.",
   brings:"protection, honest strength, the will to guard what matters without apology",
   source:"Gylfaginning, ch. 21; Thrymskvida, Poetic Edda"},

  {name:"Tyr",epithet:"the One-Handed",domain:"Justice · Oath · Sacrifice · Right Order",
   blurb:"God of law and honorable war. When the gods bound the wolf Fenrir, only Tyr would place his hand in the beast's mouth as a pledge of good faith, and only Tyr lost it when the binding held. He is the god who knows the cost of the oath and pays it anyway. Justice, to Tyr, is not comfort. It is the thing you keep even when it takes from you.",
   brings:"integrity, the courage to keep your word, sacrifice for what is right",
   source:"Gylfaginning, ch. 25 & 34, Snorri's Edda"},

  {name:"Hel",epithet:"Keeper of the Dead",domain:"Death · the Underworld · Boundary · Rest",
   blurb:"Daughter of Loki and ruler of the realm that bears her name, where those who die of sickness and age come to dwell. Half her face is living, half is death. She is not evil and not to be feared for its own sake; she is the keeper of the boundary, the one who receives what has finished its time. To honor Hel is to make peace with endings.",
   brings:"acceptance of what has ended, respect for the boundary, peace with mortality",
   source:"Gylfaginning, ch. 34 & 49, Snorri's Edda"},

  {name:"Loki",epithet:"the Sky-Traveler, the Trickster",domain:"Change · Cunning · Fire · Disruption",
   blurb:"Blood-brother to Odin and the sharpest edge among the gods. Loki is neither purely enemy nor friend; he solves the gods' problems and causes them in equal measure, and his cleverness both saves and dooms. He is the necessary disruption, the one who will not let things stay settled. Handle him knowing what he is: change itself, which serves no one's comfort.",
   brings:"adaptability, the wit to find another way, the reminder that nothing stays fixed",
   source:"Gylfaginning, ch. 33-35; Lokasenna, Poetic Edda"},

  {name:"Freyr",epithet:"Lord of the Vanir",domain:"Fertility · Harvest · Peace · Prosperity",
   blurb:"Brother of Freya and god of the fruitful earth. Freyr governs the rain and the sun on the fields, the peace in which things grow, and the prosperity of a settled people. He gave away his sword for love and will face Ragnarök without it. He is the god of plenty and of the sacrifice plenty sometimes asks, generous, life-giving, and unguarded by choice.",
   brings:"abundance, fertility of land and life, the peace that lets things flourish",
   source:"Gylfaginning, ch. 24; Skírnismál, Poetic Edda"},

  {name:"Njord",epithet:"the Sea-Father",domain:"Sea · Wind · Wealth · Safe Passage",
   blurb:"God of the sea, the wind, and the wealth they carry. Njord of the Vanir governs the coast where water meets land, the fishing and the trade, the safe return of the ship. His marriage to the mountain-goddess Skadi could not hold; he could not bear her peaks and she could not bear his shore. He is the god of the tide's give and take.",
   brings:"safe passage, provision, the wealth that comes and goes like the tide",
   source:"Gylfaginning, ch. 23, Snorri's Edda"},

  {name:"Skadi",epithet:"the Snowshoe Goddess",domain:"Winter · Mountains · the Hunt · Independence",
   blurb:"Giantess and goddess of the high cold places, the ski and the bow. Skadi came to Asgard armed, demanding recompense for her slain father, and won a place among the gods on her own terms. When her marriage to Njord failed, she returned to her mountains rather than soften. She is the goddess of the solitary height, the hunt, and the will that will not be bent.",
   brings:"self-possession, the strength of solitude, the resolve to keep your own ground",
   source:"Gylfaginning, ch. 23; Skáldskaparmál, ch. 1"},

  {name:"Heimdall",epithet:"the White God, the Watcher",domain:"Vigilance · Boundary · the Bridge · Beginnings",
   blurb:"Guardian of Bifröst, the bridge between worlds. Heimdall needs less sleep than a bird, sees to the ends of the earth, and hears the grass grow and the wool on the sheep. He holds the horn Gjallarhorn, which will sound at the end of days. He is the sentinel who never fails in his watch, the keeper of the threshold, the one who marks where one world ends and another begins.",
   brings:"vigilance, clear perception, the guarding of thresholds and beginnings",
   source:"Gylfaginning, ch. 27; Grímnismál 13"},

  {name:"Baldr",epithet:"the Shining One",domain:"Light · Purity · Grief · the Turning of Fate",
   blurb:"The bright and beloved god, so fair that light shone from him. His mother Frigg drew an oath of safety from all things save one, the mistletoe, and by that one thing he fell, guided by Loki's malice. His death is the first shadow of Ragnarök and the great grief of the gods. Yet it is said he returns after the world's ending, to walk the new green earth.",
   brings:"the value of what is bright and fragile, grief honored rather than denied, hope past the ending",
   source:"Gylfaginning, ch. 49, Snorri's Edda"},

  {name:"Nerthus",epithet:"Mother Earth",domain:"Earth · Fertility · Peace · the Sacred Wagon",
   blurb:"An ancient earth-goddess whose worship Tacitus recorded among the old tribes long before the sagas. Her image rode in a covered wagon through the land, and where she passed, weapons were laid down and peace held until she returned to her grove. She is the earth herself, older than the written gods, the peace of the land and the mystery kept behind the veil.",
   brings:"deep peace, connection to the living land, reverence for what came before",
   source:"Tacitus, Germania, ch. 40"},

  {name:"Jörð",epithet:"the Earth",domain:"Land · Ground · the Body of the World",
   blurb:"The earth given form and name, mother of Thor. Jörð is the ground underfoot made a goddess, the raw land before it is farmed or bounded, the body of the world itself. She is less storied than the high gods because she is everywhere and always, the thing they all stand upon. To honor Jörð is to honor the ground you walk and the land that holds you up.",
   brings:"grounding, belonging to place, the steadiness of the earth beneath you",
   source:"Gylfaginning, ch. 9 & 36, Snorri's Edda"},

  {name:"Rán",epithet:"the Sea-Mother",domain:"the Deep · Drowning · What the Sea Keeps",
   blurb:"Goddess of the sea's depths, who draws the drowned down into her hall with her net. Rán is not cruel so much as absolute; the sea takes what it takes, and she is the keeper of it. Sailors carried gold to pay her should they fall. She is the deep water and its danger, the beauty and the taking, the reminder that some powers are not to be bargained with lightly.",
   brings:"respect for what is deep and dangerous, acceptance of what cannot be controlled",
   source:"Skáldskaparmál, ch. 25; Helgakvida Hundingsbana I"},

  {name:"Vár",epithet:"Goddess of Oaths",domain:"Vows · Agreements · Faith Kept",
   blurb:"A goddess of the Æsir who hears the oaths and private agreements made between people, and holds them to account. Vár witnesses the vow and marks its breaking. She is invoked when promises are made, the quiet power that gives weight to a given word. In a tradition where the oath was sacred, Vár is the one who remembers what was sworn.",
   brings:"the weight of the promise, faithfulness, the power of a word truly given",
   source:"Gylfaginning, ch. 35, Snorri's Edda"},

  {name:"Idunn",epithet:"Keeper of the Apples",domain:"Youth · Renewal · Vitality · Safekeeping",
   blurb:"Guardian of the apples that keep the gods young. When Idunn was stolen away by the giant Thjazi, the gods began at once to age and grey, and only her return restored them. She is the keeper of renewal itself, the vitality that must be tended or lost. Her story is a quiet warning: the source of life's freshness is precious, and never to be taken for granted.",
   brings:"renewal, the tending of your own vitality, the freshness that must be protected",
   source:"Skáldskaparmál, ch. 1, Snorri's Edda"},

  {name:"Bragi",epithet:"the Skald of the Gods",domain:"Poetry · Eloquence · Song · Memory",
   blurb:"God of poetry and the finest of skalds, with runes carved upon his tongue. Bragi welcomes the honored dead to Valhalla with words worthy of them. He is the power of poetry to shape memory and move the heart, the craft of language raised to the sacred. In a culture that kept its history in verse, the poet's art was no small thing, and Bragi is its god.",
   brings:"eloquence, the craft of words, the power of song to carry what matters",
   source:"Skáldskaparmál, ch. 1; Gylfaginning, ch. 26"},

  {name:"Ullr",epithet:"the Glorious",domain:"the Hunt · Winter · the Bow · Single Combat",
   blurb:"God of the bow, the ski, and the winter wild, called on in single combat. Ullr is little storied but old and deep, a god of the hunt and the cold months, of skill and solitary prowess. Oaths were sworn upon his ring. He is the quiet master of the winter craft, the one who moves sure-footed over snow and strikes true from a distance.",
   brings:"skill, self-reliance, sure movement through hard seasons",
   source:"Gylfaginning, ch. 31; Grímnismál 5"},

  {name:"Sif",epithet:"the Golden-Haired",domain:"Harvest · the Home · Loyalty · Grain",
   blurb:"Wife of Thor, famed for her hair of gold, which Loki once shorn away and then replaced with true-spun gold that grew as living hair. Her golden hair is read as the ripe grain of the fields. Sif is the goddess of the harvest and the faithful hearth, the golden abundance of the settled home and the loyalty that keeps it whole.",
   brings:"faithfulness, the golden harvest, the quiet strength of the kept home",
   source:"Skáldskaparmál, ch. 35, Snorri's Edda"},

  {name:"Surtr",epithet:"the Fire Giant",domain:"Fire · Ending · Muspelheim · the Last Flame",
   blurb:"The giant of Muspelheim who guards the realm of fire with a flaming sword, and who at Ragnarök will ride out to burn the world clean. Surtr is not a god but a primal force, elder than the ordered world and present at its end. He is fire itself, the ending that clears the ground for what comes after. To name him is to name the flame that both destroys and makes new.",
   brings:"the power of endings, the fire that clears, respect for forces older than the gods",
   source:"Völuspá 52; Gylfaginning, ch. 4 & 51"},

  {name:"Vidar",epithet:"the Silent God",domain:"Vengeance · Endurance · What Survives",
   blurb:"Son of Odin, second in strength only to Thor, and the most silent of the gods. At Ragnarök, when the wolf Fenrir devours Odin, it is Vidar who avenges him and tears the wolf apart. And Vidar is among the few who survive the world's ending to walk the earth renewed. He is the quiet power that endures, the one who says little and outlasts everything.",
   brings:"endurance, quiet resolve, the strength that survives the ending",
   source:"Gylfaginning, ch. 51; Vafthrúdnismál 53"}
];

// ---- Celtic cycle, appended to the deity deck (Blackthorn Grimoire) ----
const DEITIES_CELTIC = [
  {name:"Brigid",epithet:"the Bright One, Keeper of the Flame",domain:"Hearth · Smithcraft · Healing · Sacred Speech",
   blurb:"Goddess of the forge, the healing well, and the poet's fire, honored across Ireland and Britain and later carried into the figure of the saint who shares her name. Brigid holds three crafts at once: the smith's work, the healer's work, and the making of words that ring true. She is gentle care and fierce protection in the same hand, warding the home while blessing what is created inside it. Her fire is kept, not wild.",
   brings:"warding of home and hearth, creative fire, the blessing of work done honestly",
   source:"Cormac's Glossary; Irish and Scottish folk tradition"},

  {name:"The Morrígan",epithet:"the Phantom Queen",domain:"Fate · Prophecy · Death · Battle",
   blurb:"Goddess of fate and the battlefield, appearing as crow, as washer at the ford, as three sisters who speak the shape of what is coming. She meets Cú Chulainn as lover and as enemy and is refused both times, and the refusal costs him. The Morrígan is not called for comfort; she is called when a cycle must end and the truth of it must be faced. She demands honesty and offers clarity in exchange.",
   brings:"fate made clear, the courage to end what is finished, truth without softening",
   source:"Táin Bó Cúailnge; Cath Maige Tuired"},

  {name:"Cernunnos",epithet:"the Horned One",domain:"Forest · Beasts · Wild Sovereignty · Abundance",
   blurb:"The antlered lord of the wild, shown seated among the animals with a torc in one hand and a ram-headed serpent in the other. His name survives on a single Gaulish inscription raised by a boatmen's guild in Roman-era Paris, yet his image runs across Celtic Europe, from the Gundestrup cauldron to carved stones in Britain, older and wider than the one word we have for him. The insular texts never name him; modern Druidry took up the relationship the old images imply. He is the sovereignty of the untamed, the part of the world that is not managed.",
   brings:"connection to the living land, wild sovereignty, right relationship with beasts",
   source:"Pillar of the Boatmen, Paris; Gundestrup Cauldron; honored widely in modern Druidry"},

  {name:"Cerridwen",epithet:"Keeper of the Cauldron",domain:"Transformation · Poetic Fire · Dream · Deep Wisdom",
   blurb:"Keeper of the cauldron of awen, who brewed a year and a day for her son and lost the draught to the boy set to stir it. Her pursuit of Gwion through shapes, hare and hound, fish and otter, bird and hawk, ends in his rebirth as Taliesin, the poet. Cerridwen governs the long slow work that changes a person rather than a circumstance. Her answers come slowly and arrive whole.",
   brings:"deep inner wisdom, creative trance, patience with what is still gestating",
   source:"Hanes Taliesin; the Book of Taliesin"},

  {name:"Arianrhod",epithet:"of the Silver Wheel",domain:"Stars · Soul Cycles · Rebirth · Lunar Vision",
   blurb:"Star goddess of the Fourth Branch, whose stepping over the wand reveals two sons and whose refusal of them shapes the rest of the tale. She names nothing freely and gives nothing twice, and the sons must be won from her by craft. Arianrhod is the turning wheel of soul cycles, the pattern that returns in a different form each time. She teaches by pattern rather than by word.",
   brings:"rebirth patterns, lunar vision work, memory that runs deeper than one life",
   source:"Mabinogi, Fourth Branch"},

  {name:"The Cailleach",epithet:"the Veiled One, Crone of Winter",domain:"Winter · Mountains · Storm · Shaping of the Land",
   blurb:"The old woman of winter who strikes the ground with her staff to harden it, drops stones from her creel to raise the hills, and washes her plaid in the whirlpool until the land turns white. She rules from Samhain to Beltane and holds the cold as her own season, not as an affliction. Across Scotland and Ireland she is landscape and weather made a person. She is not cruel; she is the season that asks you to endure it.",
   brings:"endurance through hard seasons, respect for the shaping powers, strength in the cold",
   source:"Scottish and Irish folk tradition"},

  {name:"Lugh",epithet:"the Many-Skilled",domain:"Sun · Mastery of Arts · Oath · Sacred Protection",
   blurb:"Lugh Lámhfhada, admitted to Tara only when he names a skill no one else there holds, and so is let in as the master of all of them together. He leads the Tuatha Dé Danann against Balor and brings the fight to its end with a stone through his grandfather's eye. Lugh is competence made sacred, the craftsman who is also the warrior and the king. His festival marks the first harvest and the games held in his foster-mother's honor.",
   brings:"mastery of craft, oath-keeping, the protection that skill provides",
   source:"Cath Maige Tuired; Lughnasadh tradition"},

  {name:"Airmid",epithet:"Keeper of the Herbs",domain:"Green Healing · Herbcraft · Restoration · Grief",
   blurb:"Healer of the Tuatha Dé Danann who laid out every herb of the world on her cloak, each in its proper order and use, until her father scattered them in jealousy and the knowledge was lost. What she gathered has never been fully recovered. Airmid is the patron of everyone who works green medicine and knows the work is partial. She teaches that healing is remembered and re-learned, never simply possessed.",
   brings:"herbcraft, patient restoration, honor for knowledge that was lost and is being regathered",
   source:"Cath Maige Tuired"},

  {name:"Sulis",epithet:"of the Hot Springs",domain:"Sacred Waters · Healing · Oaths · Petition",
   blurb:"Goddess of the hot spring at Bath, where the water comes up from the dark at a steady heat and has never stopped. Petitioners threw curse tablets into her waters asking for justice against thieves and oath-breakers, which makes her a healer and a keeper of accounts in the same breath. The Romans paired her with Minerva but the spring was hers first. She receives what is given to water.",
   brings:"healing through water, justice asked and received, petitions given to the deep",
   source:"Roman inscriptions and curse tablets, Aquae Sulis"},

  {name:"Elen of the Ways",epithet:"Guide of the Old Roads",domain:"Paths · Ley Lines · Migration · Safe Passage",
   blurb:"Elen Luyddog of the Dream of Macsen, the British woman a Roman emperor sees in a vision and crosses the world to find, who then has the great roads built across Britain so her people can move. The medieval tale makes her a road-maker and a sovereignty figure. Her more recent form as antlered guide of the trackways and reindeer paths is modern work, a living reinterpretation rather than a medieval one. Both are walked today; the practitioner should know which is which.",
   brings:"safe passage, guidance on the old roads, clarity about which way is yours",
   source:"Breuddwyd Macsen Wledig; modern reinterpretation noted"}
];

DEITIES.push(...DEITIES_CELTIC);

// ---- Plant deck, from the Blackthorn Apothecary materia ----
const PLANTS = [
 {
  "name": "Agrimony",
  "folk": "Church Steeples · Sticklewort · Fairy's Rod",
  "sub": "Air + Earth · Masculine · Jupiter · 183.58 Hz",
  "quote": "I untangle what is buried and shield what is still healing.",
  "body": "Masculine energy plant — exposes and removes hidden wounds and spiritual bindings, especially those held deep in the energetic or emotional body. Used to break curses, return negative energy, and gently reveal what must be faced. Also supports those masking pain behind politeness or denial.",
  "runes": "Algiz, Mannaz, Eihwaz",
  "deities": "Brân the Blessed, Tyr",
  "when": "Waning Moon · Late Spring through Early Fall",
  "uses": "Reversing spells, protection, banishing hidden pain",
  "caution": "Generally safe as tea or tincture. Astringent — avoid very large doses."
 },
 {
  "name": "Anise Hyssop",
  "folk": "Agastache · Licorice Mint · Blue Giant Hyssop",
  "sub": "Air · Masculine · Mercury · 141.27 Hz",
  "quote": "I bring breath to the moment and speak truth with ease and grace.",
  "body": "Masculine energy plant — lifts stagnant air and energy. Supports clear expression, deep breath, and presence. Especially useful for spiritual practitioners who use voice, sound, or breath in their work. Helps open the throat and upper chest energetically, preparing the body for invocation, song, or heartfelt speech.",
  "runes": "Ansuz, Mannaz, Ehwaz",
  "deities": "Odin, Lugh",
  "when": "Waxing Moon · Midsummer through Late Fall",
  "uses": "Clarity of speech, energetic movement, breath support, psychic awareness",
  "caution": "Generally safe and pleasant for most people. Good for regular use in teas."
 },
 {
  "name": "Basil",
  "folk": "Ocimum basilicum · Witches' Herb",
  "sub": "Fire + Air · Masculine · Mars + Mercury · 144.72 Hz",
  "quote": "I clear the path, sharpen the tongue, and energize the will.",
  "body": "Masculine energy plant — brings freshness to mental and energetic fatigue. Used to energize the spirit, aid verbal magic, and push through self-doubt. Carries a clarifying and uplifting energy ideal for ritual beginnings or empowerment rites.",
  "runes": "Raido, Ansuz, Thurisaz",
  "deities": "Hermes, Frey",
  "when": "Waxing Moon · Spring through Midsummer",
  "uses": "Clarity, courage, energetic strength, spiritual communication",
  "caution": "Safe for culinary and tea amounts. Generally well tolerated."
 },
 {
  "name": "Bay Leaves",
  "folk": "Laurel · Sweet Bay · Apollo's Leaf",
  "sub": "Fire + Air · Masculine · Sun · 126.22 Hz",
  "quote": "I call the truth forward and bless the path of courage.",
  "body": "Masculine energy plant — carries the solar current of insight, clarity, and confidence. Used to empower intention, banish illusions, and honor the voice of truth. Excellent for manifestation spells, protection, divination, and invoking divine will. Also symbolic of achievement and spiritual success.",
  "runes": "Ansuz, Sowilo, Perthro",
  "deities": "Apollo, Brân, Freyr",
  "when": "Full Moon · All seasons especially transitional",
  "uses": "Manifestation, clarity, protection, prophecy",
  "caution": "Safe in culinary amounts. Whole leaves are not edible and should be removed before consuming food."
 },
 {
  "name": "Blessed Thistle",
  "folk": "Cnicus benedictus · Holy Thistle",
  "sub": "Fire + Water · Masculine · Mars · 144.72 Hz",
  "quote": "I bring fire to infection and blessing to the wounded.",
  "body": "Masculine energy plant — used in rites of spiritual healing, boundary reinforcement, and sanctified protection. Known to stimulate the sacred will, especially when recovering from spiritual injury or intrusive energies.",
  "runes": "Thurisaz, Eiwaz, Berkano",
  "deities": "Brigid, The Morrígan (healing aspect)",
  "when": "First Quarter · Early Spring to Midsummer",
  "uses": "Protection, purification, calling in divine favor",
  "caution": "Generally safe in tea amounts as a digestive herb. Avoid in large doses during pregnancy."
 },
 {
  "name": "Blue Lotus Flower",
  "folk": "Nymphaea caerulea · Sacred Lily of the Nile · Dream Lotus",
  "sub": "Water + Spirit · Feminine · Moon + Neptune · 210.42 Hz",
  "quote": "I unfold the petals of the mind, revealing the divine in all things.",
  "body": "Feminine energy plant — sacred flower of altered states, celestial connection, and dream immersion. Gently opens the third eye and crown while softening the heart and body. Used to enter deep trance, lucid dreaming, and erotic spiritual states. A plant of the goddess, of holy longing, and the space between waking and sleep.",
  "runes": "Perthro, Laguz, Isa",
  "deities": "Aset/Isis, Freyja, Arianrhod",
  "when": "Dark Moon or Full Moon",
  "uses": "Lucid dreaming, vision work, trance, crown activation",
  "caution": "Mildly psychoactive. Use in ceremonial doses, not as a daily herb."
 },
 {
  "name": "Burdock Root",
  "folk": "Arctium lappa · Beggar's Buttons · Gobo",
  "sub": "Earth · Feminine · Venus + Saturn · 221.23 Hz / 147.85 Hz",
  "quote": "I draw the poison out and plant your roots where healing may grow.",
  "body": "Feminine energy plant — purifier and deep healer, especially in matters of ancestral burden, toxicity, and shadow pain. Digs deep and drags hidden illness — emotional, physical, or energetic — to the surface. A root of protection, grounding, and long-game healing work.",
  "runes": "Eihwaz, Othala, Naudhiz",
  "deities": "Danu, Frigg",
  "when": "Waning Moon · Autumn through Winter",
  "uses": "Purging toxins, grounding, ancestral shadow work, detoxification",
  "caution": "Generally safe. Strong liver action — use with care if on medications."
 },
 {
  "name": "Cannabis",
  "folk": "Hemp · Ganja · Sacred Green · Kánna",
  "sub": "Earth + Air · Saturn + Moon · 147.85 Hz / 210.42 Hz",
  "quote": "I soften the veil, relax the mind, and lead the spirit into layered truth.",
  "body": "Balanced polarity plant — sacred plant used across time to induce trance, soothe pain, and unlock perception. Opens the mind while grounding the body — bridging upper and lower worlds. Especially useful in dreamwork, channeling, trauma release, and intuitive development. Must be used with intention.",
  "runes": "Perthro, Ehwaz, Laguz",
  "deities": "Freyja, Odin, Green Man",
  "when": "Full or Dark Moon · Late Summer through Harvest",
  "uses": "Expanded awareness, trancework, opening perception",
  "caution": "Know your local laws. Use with full intention and grounding practice — careless use can fog the mind instead of freeing it."
 },
 {
  "name": "Chamomile",
  "folk": "Ground Apple · Whig Plant · Maythen",
  "sub": "Water · Feminine · Sun · 126.22 Hz",
  "quote": "I soften the hard places and bring peace to where chaos lingered.",
  "body": "Feminine energy plant — gentle healer used to calm, cool, and comfort. Clears emotional tension, eases mental looping, and brings the heart back into coherence. Ideal for grief processing, nervous exhaustion, sleep magic, and ritual decompression. A common ally for empaths, children, and those recovering from harsh ritual.",
  "runes": "Ehwaz, Berkano, Laguz",
  "deities": "Frigg, Airmid",
  "when": "Full or Waning Moon · Early Summer",
  "uses": "Soothing the heart, emotional processing, ritual rest",
  "caution": "Safe for most people including children in normal amounts. Rarely, may cause allergic reaction in those sensitive to the daisy family."
 },
 {
  "name": "Chicory Root",
  "folk": "Cichorium intybus · Blue Sailor's Root",
  "sub": "Earth + Air · Feminine · Jupiter + Mercury · 183.58 Hz",
  "quote": "I hold the road open and keep your will rooted.",
  "body": "Feminine energy plant — root of perseverance and grounding. Used to anchor intentions, bind spells to the body, or call back focus after disorientation. Also helpful for spiritual detoxification or navigating long-term journeys.",
  "runes": "Eiwaz, Othala, Jera",
  "deities": "Thor (as traveler), Cernunnos",
  "when": "Waning Gibbous · Late Summer to Autumn",
  "uses": "Grounding, endurance, opening roadways, stubborn magic",
  "caution": "Generally safe. Mild laxative effect in large amounts."
 },
 {
  "name": "Cinnamon",
  "folk": "Ceylon Cinnamon · Sweet Wood · Fire Bark",
  "sub": "Fire · Masculine · Sun · 126.22 Hz",
  "quote": "I bless what you build and burn away what you outgrow.",
  "body": "Masculine energy plant — powerful amplifier in spellwork. Raises vibration, activates intent, and purifies blocks. Brings warmth, clarity, and assertive joy to ritual work. Used in protection, money magic, love workings, and energy renewal.",
  "runes": "Sowilo, Fehu, Kenaz",
  "deities": "Lugh, Brigid",
  "when": "Waxing or Full Moon · Autumn through Winter",
  "uses": "Amplifying magic, success, protection, abundance, purification",
  "caution": "Strong and spicy — use with balance. Can irritate skin in excess if applied topically."
 },
 {
  "name": "Clove",
  "folk": "Syzygium aromaticum · Nail Spice",
  "sub": "Fire · Masculine · Jupiter · 183.58 Hz",
  "quote": "I drive out the dark and seal the will in fire.",
  "body": "Masculine energy plant — powerful protective and empowering herb used in warding, banishing, and strength-building rituals. Spicy heat drives out low vibration, raises spiritual defenses, and adds focused momentum to spells. Excellent for sealing intention and sharpening will.",
  "runes": "Thurisaz, Tiwaz, Sowilo",
  "deities": "Thor, Brigid",
  "when": "Waxing Moon · Autumn and Winter",
  "uses": "Protection, courage, clearing negativity, strengthening intent",
  "caution": "High in eugenol — can irritate skin and mucous membranes in excess. Use in small intentional doses."
 },
 {
  "name": "Dandelion (Root & Leaf)",
  "folk": "Lion's Tooth · Blowball · Priest's Crown",
  "sub": "Air · Masculine · Jupiter · 183.58 Hz",
  "quote": "I rise through the cracks and bring light to what was buried.",
  "body": "Masculine energy plant — plant of resilience and transformation. Supports purification of stagnant energy, release of old grief, and clarity of purpose. Use in rites of renewal, personal strength, and emotional integration. Helps restore the spirit after long periods of internal winter or energetic collapse.",
  "runes": "Kenaz, Jera, Uruz",
  "deities": "Brigid, Freyr",
  "when": "Waxing or Full Moon · Early Spring through Late Summer",
  "uses": "Purification, emotional release, renewal, clarity",
  "caution": "Generally safe for most people. Root is a strong liver tonic — use with care if on medications processed by the liver."
 },
 {
  "name": "Dittany of Crete",
  "folk": "Hop Marjoram · Origanum dictamnus · Woundwort",
  "sub": "Air + Fire · Feminine · Mercury · 141.27 Hz",
  "quote": "I guide the soul through sacred passage and protect the dreamer's flame.",
  "body": "Feminine energy plant — one of the most revered plants for astral travel, spirit summoning, and safe passage between worlds. Opens energetic portals while guarding the body and psyche during separation. Highly effective for vision questing, hedge riding, deep dreamwork, or seeking communion with guides and ancestors.",
  "runes": "Perthro, Laguz, Algiz",
  "deities": "Artemis, Brigid, Odin",
  "when": "Dark or Waxing Moon · Spring through Early Autumn",
  "uses": "Astral projection, spiritual gateways, spirit travel",
  "caution": "Use sparingly — reserved primarily for ceremonial use. Strong energetically."
 },
 {
  "name": "Earl Grey",
  "folk": "Bergamot Black Tea · Lord's Blend",
  "sub": "Air · Masculine · Mercury · 141.27 Hz",
  "quote": "I refine the message and deliver it with elegance and fire.",
  "body": "Masculine energy blend — blends black tea with bergamot making it an excellent spiritual stimulant and clarifier. Sharpens thought, lifts fog, and opens a clear channel between intention and voice. A favorite among magical practitioners for morning ritual or when poise is needed under pressure.",
  "runes": "Ansuz, Dagaz, Kenaz",
  "deities": "Odin, Brân",
  "when": "Waxing Moon · Spring through Autumn",
  "uses": "Mental clarity, eloquence, ritual focus, refined magical energy",
  "caution": "Contains caffeine. Bergamot may interact with some medications."
 },
 {
  "name": "Elderberry",
  "folk": "Black Elder · Sambucus · Hyldemoer's Gift",
  "sub": "Water · Feminine · Venus · 221.23 Hz",
  "quote": "I stand at the veil and guard the gates of life and death.",
  "body": "Feminine energy plant — deeply tied to the threshold between worlds. Respected as guardian and guide across spiritual, ancestral, and physical boundaries. Powerful in grief rituals, ancestral offerings, and protection rites involving children, the sick, or the newly deceased. Tradition warns: never cut elder without asking permission.",
  "runes": "Berkano, Laguz, Isa",
  "deities": "Freyja, Hyldemoer",
  "when": "Dark or New Moon · Late Spring through Autumn",
  "uses": "Ancestral connection, protection, grief support",
  "caution": "Stems and leaves are TOXIC — never consume. Berries must be cooked before eating raw."
 },
 {
  "name": "English Breakfast Black Tea",
  "folk": "Assam Blend · Morning Tea",
  "sub": "Fire · Masculine · Sun · 126.22 Hz",
  "quote": "I bring the light back to the mind and the fire back to the body.",
  "body": "Masculine energy blend — powerful ally for motivation, action, and clarity. Embodies the strength of the sun — direct, illuminating, energizing. Often used as a morning ritual to spark mental focus or in ceremonies requiring alertness, courage, or endurance.",
  "runes": "Sowilo, Raido, Dagaz",
  "deities": "Lugh, Baldr",
  "when": "First Quarter or Full Moon · Spring Equinox to Late Summer",
  "uses": "Energy work, clarity, motivation, awakening the will",
  "caution": "Contains caffeine. Not ideal for sensitive nervous systems in large quantities."
 },
 {
  "name": "English Lavender",
  "folk": "Lavandula angustifolia · Elf Leaf · Nard",
  "sub": "Air + Water · Feminine · Mercury + Moon · 141.27 Hz / 210.42 Hz",
  "quote": "I hush the noise and soften the world so you may hear what truly matters.",
  "body": "Feminine energy plant — one of the most beloved herbs for peace, purification, and spiritual ease. Clears tension from emotional and mental fields, allowing truth and guidance to rise gently. Ideal for dreamwork, emotional healing, and sacred rest. Holds subtle protective energy, warding against intrusive thoughtforms.",
  "runes": "Ehwaz, Laguz, Ansuz",
  "deities": "Airmid, Frigg, Brigid",
  "when": "Waning or Full Moon · Late Spring through Summer",
  "uses": "Calming the spirit, anxiety relief, dream recall, sacred sleep",
  "caution": "Very safe for most people. May potentiate sedative medications."
 },
 {
  "name": "French Celtic Sea Salt",
  "folk": "Grey Salt · Sel Gris · Salt of the Sea",
  "sub": "Earth + Water · Moon · 210.42 Hz",
  "quote": "I hold the line and dissolve what no longer belongs.",
  "body": "Neutral adaptive energy — both a clearing agent and a sacred binder, used to protect, purify, and consecrate spaces and tools. Mineral-rich structure holds grounding energy and carries the intelligence of tidal rhythms. Foundational in most traditions — clears, preserves, wards, and seals.",
  "runes": "Isa, Eiwaz, Laguz",
  "deities": "Aegir, Manannán mac Lir",
  "when": "Full or Waning Moon · All Seasons",
  "uses": "Purification, grounding, protection, banishment",
  "caution": "Food-safe in normal culinary amounts. For ritual use, not typically consumed in large quantities."
 },
 {
  "name": "Galangal Root",
  "folk": "Chewing John · Little John to Chew · Siamese Ginger",
  "sub": "Fire · Masculine · Mars · 144.72 Hz",
  "quote": "I speak with force, move with fire, and cut through what resists.",
  "body": "Masculine energy plant — sharp, fast, and decisive. Used to amplify magic, cut through energetic resistance, and strengthen intention. Supports work where you must speak with clarity and move with purpose — especially if energetically silenced or held back. Clears mental fog and enhances ritual speech.",
  "runes": "Thurisaz, Tiwaz, Ansuz",
  "deities": "Thor, Morrígan",
  "when": "Waxing Moon · Mid-Summer",
  "uses": "Commanding power, breaking through resistance, protection, confidence",
  "caution": "Strong and warming — use with balance. May irritate sensitive stomachs in excess."
 },
 {
  "name": "Ginger Root",
  "folk": "Zingiber · Fire Root · Root of Power",
  "sub": "Fire · Masculine · Mars · 144.72 Hz",
  "quote": "I spark the engine of your will and bring heat to your purpose.",
  "body": "Masculine energy plant — energizing root used to stimulate movement, ignite spells, and stir personal power into action. Wakes up stagnant spaces in both body and field. Excellent for overcoming fear, warming cold intentions, or breaking through apathy. Amplifies nearly any magical working.",
  "runes": "Uruz, Sowilo, Thurisaz",
  "deities": "Thor, Brigid",
  "when": "Waxing Moon · Winter through Spring",
  "uses": "Stamina, magical fuel, circulation, activating intention",
  "caution": "Can irritate sensitive stomachs in large amounts. May interact with blood thinners."
 },
 {
  "name": "Goat's Rue",
  "folk": "Galega officinalis · French Lilac · Professor Weed",
  "sub": "Earth + Water · Feminine · Moon + Venus · 210.42 Hz",
  "quote": "I nourish what is becoming and feed what must grow.",
  "body": "Feminine energy plant — used to foster spiritual fertility — not only of the body, but of ideas, relationships, and creation. Excellent in rituals of energetic nourishment, nurturing depleted forces, or growing intentions.",
  "runes": "Fehu, Berkano, Laguz",
  "deities": "Freyja (as fertility), Frigg",
  "when": "Waxing Moon · Spring to Early Summer",
  "uses": "Fertility magic, lactation rites, abundance, energetic nourishment",
  "caution": "Contains alkaloids that may support blood sugar regulation. May INTERACT WITH DIABETES MEDICATION."
 },
 {
  "name": "Herb Robert",
  "folk": "Geranium robertianum · Red Robin · Stinky Bob",
  "sub": "Earth + Spirit · Masculine · Mars + Saturn · 147.83 Hz",
  "quote": "I shield the subtle body and stitch spirit back into flesh.",
  "body": "Masculine energy plant — revered for its ability to restore the integrity of the aura, especially after psychic attack, emotional breakdown, or energy leeching. Encourages vitality and energetic coherence. Can be used in spiritual wound care and aura mending ceremonies.",
  "runes": "Naudhiz, Eiwaz, Algiz",
  "deities": "Odin (as wanderer-healer), The Disir",
  "when": "Dark Moon or Waning Half · Spring through Autumn",
  "uses": "Blood vitality, energetic shielding, subtle aura repair",
  "caution": "Pungent smell (part of its nature). Safe for external use."
 },
 {
  "name": "Hibiscus Flowers",
  "folk": "Roselle · Red Sorrel · Jamaica",
  "sub": "Water · Feminine · Venus · 221.23 Hz",
  "quote": "I stir the heart, flush what is false, and call forth your fire.",
  "body": "Feminine energy plant — used in spiritual work to ignite passion, enhance beauty rituals, and restore confidence. Vivid color and tart nature stimulate circulation — not only in the body but in energy. Excellent for love magic, heart healing, and solar plexus empowerment.",
  "runes": "Laguz, Berkano, Sowilo",
  "deities": "Freyja, Aphrodite",
  "when": "Full or Waxing Moon · Summer and Early Autumn",
  "uses": "Passion, self-love, emotional cleansing, vitality",
  "caution": "May lower blood pressure — avoid in large amounts if you have low blood pressure."
 },
 {
  "name": "Jamaican Blue Vervain",
  "folk": "Verbena hastata · Nervine Vervain · Spiritweed",
  "sub": "Water + Spirit · Feminine · Moon + Neptune · 210.42 Hz",
  "quote": "I loosen the knots you were told to keep silent and return the song to your blood.",
  "body": "Feminine energy plant — plant of psychic release and spirit guidance. Bitter nature mirrors its ability to unlock blocked truth. Used in healing ceremonies involving grief, trauma recall, or emotional restriction. Can help create a bridge to ancestral memory or soften internal resistance when truth must rise.",
  "runes": "Laguz, Ansuz, Mannaz",
  "deities": "Arianrhod, Frigg, The Norns",
  "when": "Dark Moon or Waning Crescent · Late Summer to Autumn",
  "uses": "Emotional release, psychic healing, grief rituals, spirit voice unlocking",
  "caution": "Very bitter — combine with sweet or warming herbs in blends. Classic nervine — gentle but effective."
 },
 {
  "name": "Lemon Balm",
  "folk": "Melissa · Heart's Delight · Sweet Balm",
  "sub": "Water · Feminine · Moon · 210.42 Hz",
  "quote": "I brighten the heart and soften the mind so the soul can breathe.",
  "body": "Feminine energy plant — gentle but powerful ally for emotional healing and heart restoration. Clears anxiety, lifts melancholy, and soothes grief without suppressing the truth. Ideal for lightening energy after heavy rituals. Supports clarity, forgiveness, and inner joy.",
  "runes": "Laguz, Sowilo, Ingwaz",
  "deities": "Aine, Sif",
  "when": "Waxing Moon · Spring through Midsummer",
  "uses": "Uplifting mood, calming nerves, emotional release, heart healing",
  "caution": "Safe for most people. May potentiate sedative medications."
 },
 {
  "name": "Lemon Peel",
  "folk": "Citrus rind · Dried Lemon Zest",
  "sub": "Fire + Air · Feminine · Sun · 126.22 Hz",
  "quote": "I slice through mental haze and uplift the spirit with sunlit laughter and breath.",
  "body": "Feminine energy plant — brings the spirit of cleansing and cheerful resilience. Awakens the senses and clears lingering emotional fog. Excellent for energy cleansing rituals, intention-setting ceremonies, or spells requiring mental sharpness. Can lighten heavy emotional states and enhance the solar plexus.",
  "runes": "Sowilo, Dagaz, Ansuz",
  "deities": "Freyja (joy aspect), Baldur, Brigid",
  "when": "Waxing Crescent or Full Moon · Late Winter through Spring",
  "uses": "Mental clarity, joy, purification, energy clearing",
  "caution": "Generally safe in food and tea amounts. Use food-grade, organic lemon peel when possible — avoid peels treated with pesticides."
 },
 {
  "name": "Licorice Root",
  "folk": "Sweet Root · Glycyrrhiza · Voice Root",
  "sub": "Water + Air · Feminine · Venus · 221.23 Hz",
  "quote": "I sweeten the voice and bind the words to heart and truth.",
  "body": "Feminine energy plant — both a harmonizer and binder. Used to unify energies within a spell and to sweeten speech, intentions, and communication. Draws what is scattered back into alignment and helps integrate disparate energies in ritual. Assists in negotiations, relationship healing, and attracting support.",
  "runes": "Ansuz, Laguz, Ingwaz",
  "deities": "Brigid, Freyja",
  "when": "Waxing or Full Moon · Late Spring through Autumn",
  "uses": "Soothing communication, harmonizing conflict, self-expression, binding",
  "caution": "Should be used in moderation. Avoid in cases of high blood pressure, kidney issues, or heart conditions."
 },
 {
  "name": "Marshmallow Root",
  "folk": "Althaea officinalis · Mallow",
  "sub": "Water + Earth · Feminine · Venus · 221.23 Hz",
  "quote": "I quiet the wounded places and line the soul with softness.",
  "body": "Feminine energy plant — soothing ally for spiritual inflammation or trauma shock. Used to comfort inner child work, grief rites, or tender emotional release. Its softening nature helps create safe space for deeper healing or ancestral contact.",
  "runes": "Laguz, Isa, Berkano",
  "deities": "Frigg, Danu",
  "when": "Waning Crescent · Late Autumn",
  "uses": "Soothing, spiritual softening, holding sacred grief",
  "caution": "Very safe and gentle. Excellent for dry, inflamed, or irritated conditions."
 },
 {
  "name": "Mugwort",
  "folk": "Artemisia · Dreamweed · Traveler's Protection",
  "sub": "Air · Feminine · Moon · 210.42 Hz",
  "quote": "I walk with you at the edge of worlds and guard your return.",
  "body": "Feminine energy plant — one of the most essential herbs for second sight, liminal journeying, and protective trancework. Traditional ally for seers, witches, and travelers. Burned, steeped, or worn, Mugwort guides the mind into altered states while guarding the spiritual edge.",
  "runes": "Eiwaz, Perthro, Laguz",
  "deities": "Freyja, Hecate, Arianrhod",
  "when": "Full or Dark Moon · Midsummer through Autumn",
  "uses": "Protection in travel, dreamwork, divination, trance",
  "caution": "NOT for use during pregnancy — can stimulate uterine contractions. Do not use internally in large amounts."
 },
 {
  "name": "Nettle",
  "folk": "Stinging Nettle · Urtica · Devil's Leaf",
  "sub": "Earth · Masculine · Mars · 144.72 Hz",
  "quote": "I fortify your edges and return your strength to center.",
  "body": "Masculine energy plant — fierce ally for those who feel depleted, scattered, or overwhelmed. Restores boundaries, awakens the will, and brings the body and soul into firm alignment. Especially potent for recovering from burnout, spiritual overexposure, or long periods of energetic weakness. Acts as both shield and fuel.",
  "runes": "Uruz, Eihwaz, Othala",
  "deities": "Eir, Freyja",
  "when": "Waxing Moon · Spring and Early Summer",
  "uses": "Protection, vitality, blood strength, fortification",
  "caution": "Handle fresh plant with gloves — stings. Generally safe to consume when cooked or dried."
 },
 {
  "name": "Oregon Oxalis (Wood Sorrel)",
  "folk": "Oxalis oregana · Sourgrass · Fairy Clover",
  "sub": "Earth + Water · Feminine · Venus + Moon · 221.23 Hz",
  "quote": "I soften pride and root your soul where moss holds memory.",
  "body": "Feminine energy plant — brings a spirit of humility, quiet intuition, and soft emotional release. Used to rebalance emotional intensity, attract small blessings, or reconnect with woodland spirits and fae kin.",
  "runes": "Laguz, Eiwaz, Perthro",
  "deities": "Danu, Frigg, The Norns",
  "when": "Waning Crescent or New Moon · Spring to Early Summer",
  "uses": "Luck, humility, emotional reset, fae connection",
  "caution": "High in oxalic acid — consume in moderation. Not for large or frequent internal doses."
 },
 {
  "name": "Peppermint",
  "folk": "Mentha piperita · Brighid's Leaf · Breath of Wind",
  "sub": "Air · Masculine · Mercury · 141.27 Hz",
  "quote": "I stir the mind awake and sweep away the clouded lies.",
  "body": "Masculine energy plant — invigorating, clear, and cleansing. Used to cut through mental fog, cleanse ritual space, and stimulate the senses. Excellent for fresh starts, mental sharpness, and removing spiritual stagnation or confusion.",
  "runes": "Ansuz, Raido, Laguz",
  "deities": "Brigid, Odin",
  "when": "Waxing Moon · Spring through Summer",
  "uses": "Energizing, mental clarity, spiritual wakefulness, banishment of confusion",
  "caution": "Safe for most people. Avoid in infants (menthol can suppress breathing reflex)."
 },
 {
  "name": "Plantain Leaf",
  "folk": "Waybread · White Man's Foot · Broadleaf Plantain",
  "sub": "Earth · Feminine · Venus · 221.23 Hz",
  "quote": "I draw out what does not belong and restore grounded wholeness.",
  "body": "Feminine energy plant — earthy stabilizer tied to drawing out harm — whether physical poisons or spiritual sludge. Calms overextended energy, anchors the soul, and supports integration after spiritual fragmentation. Especially supportive for those who carry others' wounds or feel overly porous in spiritual environments.",
  "runes": "Berkano, Uruz",
  "deities": "Eir, Green Man",
  "when": "Waxing Moon · Spring through Late Summer",
  "uses": "Drawing out toxins, grounding, healing",
  "caution": "Generally safe in teas and washes. Safe for most people."
 },
 {
  "name": "Powdered Douglas Fir Bark",
  "folk": "Pseudotsuga menziesii · Forest Elder · Westwood",
  "sub": "Earth + Air · Masculine · Jupiter + Saturn · 183.58 Hz / 147.85 Hz",
  "quote": "I anchor the spirit, guard the threshold, and root your oath to earth and sky.",
  "body": "Masculine energy plant — guardian of the threshold. A tree of strength, endurance, and deep forest wisdom. Its bark connects us to ancestral memory, sacred land spirits, and long-held truth. Used in protection spells, land offerings, grounding rites, and boundary work. Stabilizes the energy body and reclaims scattered power.",
  "runes": "Eiwaz, Othala, Algiz",
  "deities": "Thor, Tyr, Dôn",
  "when": "Waning or Full Moon · Winter Solstice through Spring",
  "uses": "Grounding, protection, ancestral connection, land blessing",
  "caution": "Best used externally or as smoke. Can be infused into oils or salves."
 },
 {
  "name": "Rama Holy Basil",
  "folk": "Tulsi · Sacred Basil · Queen of Herbs",
  "sub": "Air + Fire · Feminine · Sun · 126.22 Hz",
  "quote": "I lift the spirit, purify the path, and protect what is true.",
  "body": "Feminine energy plant — revered as a purifier of body, mind, and soul. Cleanses the energy field, uplifts mood, and restores spiritual harmony. Dispels spiritual dissonance and supports heart-centered awareness. Excellent for balancing logic and intuition, especially after trauma or internal fragmentation.",
  "runes": "Sowilo, Eiwaz, Berkano",
  "deities": "Freyja, Sunna",
  "when": "Waxing or Full Moon · Spring through Late Summer",
  "uses": "Spiritual elevation, energetic purification, resilience",
  "caution": "Generally safe for regular use. May affect thyroid function with extremely heavy long-term use."
 },
 {
  "name": "Rooibos",
  "folk": "Red Bush · Aspalathus linearis",
  "sub": "Earth + Fire · Neutral · Sun · 126.22 Hz",
  "quote": "I nourish the strength within and warm the way ahead.",
  "body": "Neutral plant — grounding and nourishing herb that carries the warmth of sunlight without overstimulation. Used in spiritual recovery, rest cycles, and rites of replenishment. Provides soft strength and helps rebuild emotional and physical energy. Excellent for solar alignments and protective rites involving children or sensitive individuals.",
  "runes": "Uruz, Sowilo, Berkano",
  "deities": "Sunna, Airmid",
  "when": "Any (especially Full Moon) · Late Summer through Autumn",
  "uses": "Restoration, inner strength, grounding, vitality",
  "caution": "Caffeine-free. Suitable for nearly all constitutions including children and the elderly."
 },
 {
  "name": "Rose Bud Petals",
  "folk": "Rosa · Queen of Flowers · Heart's Bloom",
  "sub": "Water + Earth · Feminine · Venus · 221.23 Hz",
  "quote": "I open the heart to beauty, even through sorrow, and call in softness as strength.",
  "body": "Feminine energy plant — used to soften, awaken, and bless. Bridge between sorrow and joy, making it potent in grief rituals, self-forgiveness work, and divine feminine devotion. Helps clear emotional pain, reconnect to softness, and hold the heart in sacred balance.",
  "runes": "Berkano, Laguz, Ingwaz",
  "deities": "Freyja, Brigid, Epona",
  "when": "Full Moon · Spring through Summer Solstice",
  "uses": "Self-love, grief healing, heart opening, emotional alchemy",
  "caution": "Very safe and gentle. Suitable for regular use."
 },
 {
  "name": "Rosemary",
  "folk": "Dew of the Sea · Elfin Plant · Rosmarinus",
  "sub": "Fire + Air · Masculine · Sun · 126.22 Hz",
  "quote": "I burn clear the space between, and anchor what must be remembered.",
  "body": "Masculine energy plant — clears, protects, and revives. One of the most revered herbs for spiritual purification and clearing sacred space. Strengthens memory — not just mental recall, but soul memory, ancestral roots, and karmic patterns. Often used in rites of passage, seasonal shifts, and ritual rebirth.",
  "runes": "Sowilo, Ansuz, Othala",
  "deities": "Freyr, Brigid, Apollo",
  "when": "Full Moon · All seasons (especially Winter to Spring)",
  "uses": "Protection, memory, purification, ancestral connection",
  "caution": "Safe in culinary and moderate tea amounts. Avoid high medicinal doses during pregnancy."
 },
 {
  "name": "Rue",
  "folk": "Herb of Grace · Ruta · Witchbane",
  "sub": "Fire · Feminine · Mars · 144.72 Hz",
  "quote": "I break what binds and shield what is sacred.",
  "body": "Feminine energy plant — used for uncrossing, energetic severing, and enforcing clear boundaries after contact with unwanted forces. Rue supports the end of spiritual contracts, clears lingering energies, and fortifies protection rites. Often used after deep shadow work, grief release, or spiritual extraction.",
  "runes": "Thurisaz, Eiwaz",
  "deities": "Thor, Cailleach",
  "when": "Waning Moon · Late Summer",
  "uses": "Banishing, boundary-setting, cord-cutting, curse-breaking",
  "caution": "TOXIC in large amounts. NOT safe during pregnancy."
 },
 {
  "name": "Sassafras Bark",
  "folk": "Root Beer Tree · Saxifrax · Green Stick",
  "sub": "Fire · Masculine · Jupiter · 183.58 Hz",
  "quote": "I clear the crossroads and awaken the path beneath your feet.",
  "body": "Masculine energy plant — bright, clearing plant used for road opening, personal renewal, and breaking out of stuck patterns. Acts like spiritual kindling — lighting fires where energy has gone cold. Used in prosperity workings, intention setting, and seasonal rites of initiation when seeking to reclaim will or momentum.",
  "runes": "Dagaz, Raido, Sowilo",
  "deities": "Dagda, Freyr",
  "when": "First Quarter · Spring and Early Summer",
  "uses": "Road opening, personal empowerment, prosperity",
  "caution": "Contains safrole — limit to occasional ritual tea, not for daily or large-dose use."
 },
 {
  "name": "Star Anise",
  "folk": "Badian · Star Spice · Illixi",
  "sub": "Air · Masculine · Jupiter · 183.58 Hz",
  "quote": "I open the gate of vision and guide the word to where it matters.",
  "body": "Masculine energy plant — star-shaped spice that awakens perception, deepens intuition, and supports clear communication across spiritual planes. Stimulates mental clarity and symbolic language recognition. Excellent when messages are unclear or preparing the mind for prophecy, trance, or ritual speech.",
  "runes": "Ansuz, Kenaz, Perthro",
  "deities": "Odin, Danu",
  "when": "Waxing or Full Moon · Autumn through Winter",
  "uses": "Divination, insight, spirit communication, spell enhancement",
  "caution": "IMPORTANT: Must be distinguished from Japanese Star Anise, which is TOXIC."
 },
 {
  "name": "Tobacco (Aztec Type)",
  "folk": "Mapacho · Sacred Tobacco · Nicotiana rustica",
  "sub": "Earth + Fire · Masculine · Mars + Saturn · 144.72 Hz / 147.85 Hz",
  "quote": "I carry the words to the flame, and demand truth in return.",
  "body": "Masculine energy plant — NOT a casual smoke. A spiritual bridge, sacred offering, and power amplifier. Used to open rituals, call to the spirits, and seal energetic contracts or wardings. Excellent in land offerings, banishment rites, and moments of deep commitment. Tobacco's spirit is demanding, but loyal when honored properly.",
  "runes": "Thurisaz, Isa, Tiwaz",
  "deities": "Tezcatlipoca, Odin, Cernunnos",
  "when": "Dark or Full Moon · Late Summer to Autumn Equinox",
  "uses": "Offerings, prayer transmission, energetic sealing, calling spirits",
  "caution": "NOT for casual use. Aztec-type (Nicotiana rustica) is far stronger than commercial tobacco."
 },
 {
  "name": "White Sage",
  "folk": "Salvia apiana · Grandmother Sage",
  "sub": "Fire + Air · Masculine · Sun + Mars · 126.22 Hz",
  "quote": "I burn clean what lingers and return the path to flame.",
  "body": "Masculine energy plant — powerful purifier and protective force. Used to cast out lingering energies, clear stagnant attachments, and invite protective spirits. Works best when combined with clear intent and spoken word. Use responsibly and honor cultural roots.",
  "runes": "Thurisaz, Sowilo, Algiz",
  "deities": "Thor, Brigid (as flame)",
  "when": "Full Moon · High Summer",
  "uses": "Purification, spiritual fire, protection",
  "caution": "Use responsibly and honor Indigenous cultural context — Salvia apiana is sacred to many Native American peoples."
 },
 {
  "name": "Wild Ginger",
  "folk": "Asarum caudatum · Long-Tailed Wild Ginger",
  "sub": "Earth + Fire · Masculine · Mars + Saturn · 147.83 Hz",
  "quote": "I stir fire in the roots and memory in the bones.",
  "body": "Masculine energy plant — hidden ally of deep protection and inner fire. Known to reveal ancestral strengths or awaken latent spiritual paths. Used in land honoring rites or deep healing ceremonies where emotional or ancestral patterning must be burned clean.",
  "runes": "Eiwaz, Thurisaz, Kenaz",
  "deities": "Thor, Cernunnos, Brigid",
  "when": "First Quarter or Waning Moon · Autumn through Winter",
  "uses": "Protection, hidden power, ancestral awakening",
  "caution": "Use in small doses — strong flavor and energy. Best used in small, intentional amounts."
 },
 {
  "name": "Wormwood",
  "folk": "Artemisia absinthium · Dark Moon Herb · Bitter Sage",
  "sub": "Fire + Air · Masculine · Mars · 144.72 Hz",
  "quote": "I reveal the truth beneath decay and guard the gate to the unseen.",
  "body": "Masculine energy plant — powerful banishing and vision herb. Reveals what is hidden, clears attachments, and opens doorways to the Otherworld. Used for spirit communication, psychic shielding, and dealing with restless dead or trickster energies. Its bitterness cuts through illusion.",
  "runes": "Thurisaz, Perthro, Eihwaz",
  "deities": "Odin, Hekate, The Morrígan",
  "when": "Waning or Dark Moon · Late Summer through Samhain",
  "uses": "Spirit banishing, vision questing, death rites, psychic power",
  "caution": "NOT for long-term internal use — strong and potentially toxic in excess."
 },
 {
  "name": "Yarrow",
  "folk": "Soldier's Woundwort · Nosebleed Plant · Milfoil",
  "sub": "Air · Feminine · Mars · 144.72 Hz",
  "quote": "I seal the edges of your soul and make your boundaries whole.",
  "body": "Feminine energy plant — ancient ally of protection and sight. Holds tension while allowing clear vision. Ideal before or after ritual exposure, dreamwork, or any journeying where the energetic field might fray. Stops energetic bleeding — when you've given too much, absorbed too much, or left part of yourself behind.",
  "runes": "Algiz, Sowilo, Eiwaz",
  "deities": "Odin, Brigid",
  "when": "Full or Waning Moon · Late Spring to Midsummer",
  "uses": "Psychic shielding, sealing aura leaks, divination support",
  "caution": "Strong herb — use with respect. Can be made into tea but use moderately."
 }
];
